services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: atlas-api:latest
    container_name: atlas-api
    restart: unless-stopped
    env_file:
      - api/.env
    ports:
      - "8000:8000"

  agent:
    build:
      context: .
      dockerfile: llm-gateway/Dockerfile
    image: atlas-agent:latest
    container_name: atlas-llm-gateway
    restart: unless-stopped
    env_file:
      - llm-gateway/.env
    ports:
      - "8001:8001"
