"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { ProjectDetails, ProjectType, ResolveDocumentsResponse } from "@/types/consent";
import {
  type ChecklistResult,
  type CompletionRecord,
  createSubmissionPackageRecord,
  createManualDocumentRecord,
  getOrderedDocumentIds,
  type ManualConsentDocumentInput,
  normalizeDocuments,
  type StoredManualConsentDocument,
  type ConsentDocument,
  type SubmissionPackage,
  type UploadRecord,
  getCompletionStats,
  isManualDocument,
  slugifyDocument,
} from "./model";
import {
  type ConsentAssessmentRow,
  EMPTY_ROW,
  browserClient,
  loadConsentAssessment,
  saveConsentAssessment,
} from "./persistence";

export interface ProjectIntake {
  projectType: string;
  estimatedFloorAreaM2?: number | null;
  estimatedConstructionValueNZD?: number | null;
  involvesStructuralWork?: boolean;
  involvesEarthworks?: boolean;
  existingStructureDemolished?: boolean;
  newRoadAccess?: boolean;
  serviceConnectionWater?: boolean;
  serviceConnectionWastewater?: boolean;
  serviceConnectionStormwater?: boolean;
  yearOfConstruction?: number | null;
}

interface UseConsentAssessmentOptions {
  projectId: string;
  address: string;
  projectDetails?: ProjectDetails;
  projectIntake?: ProjectIntake;
}

export function useConsentAssessment({
  projectId,
  address,
  projectDetails,
  projectIntake,
}: UseConsentAssessmentOptions) {
  const requestIdRef = useRef(0);
  const hasAutoGeneratedRef = useRef(false);
  const supabaseRef = useRef(browserClient());
  const [state, setState] = useState<ConsentAssessmentRow>(EMPTY_ROW);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasHydrated, setHasHydrated] = useState(false);

  useEffect(() => {
    let cancelled = false;
    hasAutoGeneratedRef.current = false;
    setHasHydrated(false);
    void (async () => {
      const row = await loadConsentAssessment(supabaseRef.current, projectId);
      if (cancelled) return;
      requestIdRef.current += 1;
      setState(row);
      setError(null);
      setIsLoading(false);
      setHasHydrated(true);
    })();
    return () => {
      cancelled = true;
    };
  }, [projectId]);

  useEffect(() => {
    if (!hasHydrated || isLoading || error || state.checklist || !address || hasAutoGeneratedRef.current) {
      return;
    }
    hasAutoGeneratedRef.current = true;
    void generateChecklist();
  }, [address, error, hasHydrated, isLoading, state.checklist]);

  const documents = useMemo<ConsentDocument[]>(
    () =>
      normalizeDocuments(
        state.checklist?.required_documents ?? [],
        state.manualDocuments,
        state.hiddenDocumentIds,
        state.documentOrder,
      ),
    [state],
  );

  const documentMap = useMemo(
    () => new Map(documents.map((document) => [document.id, document])),
    [documents],
  );

  const completion = useMemo(
    () => getCompletionStats(documents, state.completions),
    [documents, state.completions],
  );
  const submissionPackageMap = useMemo(
    () => new Map<string, SubmissionPackage>(state.submissionPackages.map((item) => [item.id, item])),
    [state.submissionPackages],
  );

  function commitState(
    updater: (current: ConsentAssessmentRow) => ConsentAssessmentRow,
  ) {
    setState((current) => {
      const next = updater(current);
      void saveConsentAssessment(supabaseRef.current, projectId, next);
      return next;
    });
  }

  async function generateChecklist() {
    if (!address) {
      setError("Project address is required before a consent checklist can be generated.");
      return;
    }

    const requestId = requestIdRef.current + 1;
    requestIdRef.current = requestId;
    setIsLoading(true);
    setError(null);

    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000";
      const response = await fetch(`${apiUrl}/address-to-checklist`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ address, city: "", postalcode: "" }),
      });

      if (!response.ok) {
        const payload = await response.json().catch(() => null);
        throw new Error(formatApiError(payload) || "Failed to generate consent checklist.");
      }

      const payload = (await response.json()) as ChecklistResult;
      if (requestIdRef.current !== requestId) {
        return;
      }

      const effectiveDetails =
        projectDetails ?? intakeToProjectDetails(projectIntake);
      let resolvedDocuments: ResolveDocumentsResponse["documents"] = [];
      try {
        const resolved = await resolveProjectDocuments(apiUrl, payload, effectiveDetails);
        resolvedDocuments = resolved.documents ?? [];
      } catch (resolveError) {
        console.warn(
          "[consent-assessment] resolve-documents failed during checklist generation",
          resolveError instanceof Error ? resolveError.message : String(resolveError),
        );
      }
      const nextChecklist: ChecklistResult = {
        ...payload,
        required_documents: ensureNationalBaselineDocuments(
          mergeRequiredDocuments(payload.required_documents, resolvedDocuments),
        ),
      };

      const nextForecastContext = buildForecastContext(
        address,
        nextChecklist,
        projectIntake,
      );

      commitState((current) => ({
        ...current,
        checklist: nextChecklist,
        forecastContext: nextForecastContext,
      }));
    } catch (requestError) {
      if (requestIdRef.current !== requestId) {
        return;
      }

      setError(
        requestError instanceof Error
          ? requestError.message
          : "An unexpected error occurred while generating the checklist.",
      );
    } finally {
      if (requestIdRef.current === requestId) {
        setIsLoading(false);
      }
    }
  }

  function createManualDocument(input: ManualConsentDocumentInput, file?: File | null) {
    const record = createManualDocumentRecord(input);

    commitState((current) => {
      const nextCompletions = { ...current.completions };

      if (input.completed) {
        nextCompletions[record.id] = { completedAt: new Date().toISOString() };
      }

      return {
        ...current,
        manualDocuments: [...current.manualDocuments, record],
        hiddenDocumentIds: current.hiddenDocumentIds.filter((id) => id !== record.id),
        documentOrder: [...current.documentOrder.filter((id) => id !== record.id), record.id],
        completions: nextCompletions,
      };
    });

    return record.id;
  }

  function removeDocument(documentId: string) {
    commitState((current) => {
      const currentDocuments = getDocumentsForState(current);
      const target = currentDocuments.find((document) => document.id === documentId);
      const nextCompletions = { ...current.completions };
      const nextUploads = { ...current.uploads };
      const nextSubmissionIds = { ...current.documentSubmissionIds };

      delete nextCompletions[documentId];
      delete nextUploads[documentId];
      delete nextSubmissionIds[documentId];

      return {
        ...current,
        manualDocuments: isManualDocument(target)
          ? current.manualDocuments.filter((document) => document.id !== documentId)
          : current.manualDocuments,
        hiddenDocumentIds: isManualDocument(target)
          ? current.hiddenDocumentIds.filter((id) => id !== documentId)
          : Array.from(new Set([...current.hiddenDocumentIds, documentId])),
        documentOrder: current.documentOrder.filter((id) => id !== documentId),
        completions: nextCompletions,
        uploads: nextUploads,
        documentSubmissionIds: nextSubmissionIds,
      };
    });
  }

  function createSubmissionPackage(title: string, documentIds: string[]) {
    const normalizedTitle = title.trim();
    const uniqueDocumentIds = Array.from(
      new Set(documentIds.filter((documentId) => documentMap.has(documentId))),
    );
    if (!normalizedTitle || uniqueDocumentIds.length === 0) {
      return null;
    }

    const submissionPackage = createSubmissionPackageRecord(projectId, normalizedTitle);

    commitState((current) => {
      const nextSubmissionIds = { ...current.documentSubmissionIds };
      for (const documentId of uniqueDocumentIds) {
        nextSubmissionIds[documentId] = submissionPackage.id;
      }

      return {
        ...current,
        submissionPackages: [submissionPackage, ...current.submissionPackages],
        documentSubmissionIds: nextSubmissionIds,
      };
    });

    return submissionPackage.id;
  }

  function deleteSubmissionPackage(submissionId: string) {
    let found = false;

    commitState((current) => {
      const nextSubmissionPackages = current.submissionPackages.filter((submissionPackage) => {
        const matches = submissionPackage.id === submissionId;
        if (matches) {
          found = true;
        }
        return !matches;
      });
      const nextSubmissionIds = Object.fromEntries(
        Object.entries(current.documentSubmissionIds).filter(([, value]) => value !== submissionId),
      );

      return {
        ...current,
        submissionPackages: nextSubmissionPackages,
        documentSubmissionIds: nextSubmissionIds,
      };
    });

    return found;
  }

  function updateSubmissionPackageCouncilUrl(submissionId: string, value: string) {
    const normalizedCouncilUrl = normalizeCouncilUrl(value);
    let found = false;

    commitState((current) => ({
      ...current,
      submissionPackages: current.submissionPackages.map((submissionPackage) => {
        if (submissionPackage.id !== submissionId) {
          return submissionPackage;
        }

        found = true;
        return {
          ...submissionPackage,
          councilUrl: normalizedCouncilUrl,
        };
      }),
    }));

    return found;
  }

  function saveDocumentOrder(nextDocumentOrder: string[]) {
    commitState((current) => ({
      ...current,
      documentOrder: nextDocumentOrder,
    }));
  }

  function resetDocumentOrder() {
    commitState((current) => ({
      ...current,
      documentOrder: getOrderedDocumentIds(
        normalizeDocuments(
          current.checklist?.required_documents ?? [],
          current.manualDocuments,
          current.hiddenDocumentIds,
          [],
        ),
      ),
    }));
  }

  async function saveUpload(documentId: string, file: File) {
    const document = documentMap.get(documentId);
    if (!document) {
      throw new Error("Document not found.");
    }

    const safeName = file.name.replace(/\s+/g, "_");
    const storagePath = `${projectId}/consent-assessment/${documentId}/${Date.now()}-${safeName}`;
    const { error: storageError } = await supabaseRef.current.storage
      .from("attachments")
      .upload(storagePath, file, { upsert: false, contentType: file.type });
    if (storageError) throw storageError;

    const baseRecord = {
      project_id: projectId,
      filename: file.name,
      storage_path: storagePath,
      mime_type: file.type || null,
      size_bytes: file.size,
    };
    const { data: inserted, error: insertError } = await supabaseRef.current
      .from("attachments")
      .insert({
        ...baseRecord,
        linked_requirement_key: documentId,
        linked_requirement_label: document.title,
        linked_requirement_source: "consent_assessment",
        display_name: document.title,
      })
      .select("id, filename, storage_path, uploaded_at, size_bytes, mime_type")
      .single();

    const uploadRecord =
      insertError || !inserted
        ? await insertConsentAttachmentFallback(supabaseRef.current, baseRecord)
        : {
            id: inserted.id,
            fileName: inserted.filename,
            fileSize: Number(inserted.size_bytes ?? file.size),
            uploadedAt: inserted.uploaded_at,
            storagePath: inserted.storage_path,
            mimeType: inserted.mime_type ?? null,
          };

    commitState((current) => ({
      ...current,
      uploads: {
        ...current.uploads,
        [documentId]: [...(current.uploads[documentId] ?? []), uploadRecord],
      },
    }));
  }

  async function removeUpload(documentId: string, uploadId: string) {
    const upload = (state.uploads[documentId] ?? []).find((item) => item.id === uploadId);
    if (!upload) return;

    const { error: storageError } = await supabaseRef.current.storage
      .from("attachments")
      .remove([upload.storagePath]);
    if (storageError) throw storageError;

    const { error: deleteError } = await supabaseRef.current
      .from("attachments")
      .delete()
      .eq("id", upload.id);
    if (deleteError) throw deleteError;

    commitState((current) => {
      const nextUploads = { ...current.uploads };
      const remaining = (nextUploads[documentId] ?? []).filter((item) => item.id !== uploadId);
      if (remaining.length > 0) {
        nextUploads[documentId] = remaining;
      } else {
        delete nextUploads[documentId];
      }

      return {
        ...current,
        uploads: nextUploads,
      };
    });
  }

  function setDocumentCompleted(documentId: string, checked: boolean) {
    commitState((current) => {
      const nextCompletions = { ...current.completions };

      if (checked) {
        nextCompletions[documentId] = { completedAt: new Date().toISOString() };
      } else {
        delete nextCompletions[documentId];
      }

      return {
        ...current,
        completions: nextCompletions,
      };
    });
  }

  return {
    checklist: state.checklist,
    documents,
    documentMap,
    manualDocuments: state.manualDocuments,
    hiddenDocumentIds: state.hiddenDocumentIds,
    documentOrder: state.documentOrder,
    uploads: state.uploads,
    completions: state.completions,
    forecastContext: state.forecastContext,
    submissionPackages: state.submissionPackages,
    documentSubmissionIds: state.documentSubmissionIds,
    submissionPackageMap,
    completion,
    isLoading,
    error,
    hasHydrated,
    generateChecklist,
    createManualDocument,
    createSubmissionPackage,
    deleteSubmissionPackage,
    updateSubmissionPackageCouncilUrl,
    removeDocument,
    saveDocumentOrder,
    resetDocumentOrder,
    saveUpload,
    removeUpload,
    setDocumentCompleted,
  };
}

function normalizeCouncilUrl(value: string) {
  const normalized = value.trim();
  if (!normalized) {
    return null;
  }

  let parsed: URL;
  try {
    parsed = new URL(normalized);
  } catch {
    throw new Error("Council submission link must be a valid URL.");
  }

  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    throw new Error("Council submission link must start with http:// or https://.");
  }

  return parsed.toString();
}

function intakeToProjectDetails(
  intake: ProjectIntake | undefined,
): ProjectDetails {
  const allowedTypes: ProjectType[] = [
    "new_dwelling",
    "extension",
    "accessory_building",
    "deck",
  ];
  const rawType = (intake?.projectType ?? "new_dwelling") as ProjectType;
  const projectType: ProjectType = allowedTypes.includes(rawType)
    ? rawType
    : "new_dwelling";
  return {
    projectType,
    estimatedFloorAreaM2: intake?.estimatedFloorAreaM2 ?? null,
    estimatedConstructionValueNZD: intake?.estimatedConstructionValueNZD ?? null,
    involvesStructuralWork: intake?.involvesStructuralWork ?? false,
    involvesEarthworks: intake?.involvesEarthworks ?? false,
    existingStructureDemolished: intake?.existingStructureDemolished ?? false,
    yearOfConstruction: intake?.yearOfConstruction ?? null,
    newRoadAccess: intake?.newRoadAccess ?? false,
    newServiceConnections: {
      water: intake?.serviceConnectionWater ?? false,
      wastewater: intake?.serviceConnectionWastewater ?? false,
      stormwater: intake?.serviceConnectionStormwater ?? false,
    },
  };
}

async function resolveProjectDocuments(
  apiUrl: string,
  checklist: ChecklistResult,
  projectDetails: ProjectDetails,
) {
  const response = await fetch(`${apiUrl}/api/resolve-documents`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      zoneCategory: getZoneCategory(checklist.zone_info?.zone_type),
      activeOverlays: Object.entries(checklist.overlays ?? {})
        .filter(([, isActive]) => isActive)
        .map(([key]) => normalizeOverlayKey(key))
        .filter((key): key is string => Boolean(key)),
      projectDetails,
    }),
  });

  if (!response.ok) {
    const payload = await response.json().catch(() => null);
    throw new Error(formatApiError(payload) || "Failed to resolve consent documents.");
  }

  return (await response.json()) as ResolveDocumentsResponse;
}

function mergeRequiredDocuments(
  addressDocuments: ChecklistResult["required_documents"],
  resolvedDocuments: ResolveDocumentsResponse["documents"],
) {
  const merged = new Map<string, ChecklistResult["required_documents"][number]>();

  for (const document of addressDocuments) {
    merged.set(slugifyDocument(document.document_type), {
      ...document,
      triggered_by: [...document.triggered_by],
    });
  }

  for (const document of resolvedDocuments) {
    const key = slugifyDocument(document.title);
    const existing = merged.get(key);
    const nextTriggeredBy = buildResolvedDocumentTriggers(document);

    if (existing) {
      merged.set(key, {
        ...existing,
        category: existing.category || document.category,
        reason: mergeReason(existing.reason, document.description),
        triggered_by: Array.from(new Set([...existing.triggered_by, ...nextTriggeredBy])),
      });
      continue;
    }

    merged.set(key, {
      document_type: document.title,
      category: document.category,
      reason: document.description,
      triggered_by: nextTriggeredBy,
    });
  }

  return Array.from(merged.values());
}

function ensureNationalBaselineDocuments(
  documents: ChecklistResult["required_documents"],
): ChecklistResult["required_documents"] {
  const hasForm2 = documents.some((doc) => /form\s*2/i.test(doc.document_type));
  if (hasForm2) return documents;

  return [
    ...documents,
    {
      document_type: "Form 2 Building Consent Application",
      category: "baseline",
      reason:
        "National standard building consent application form required for lodgement.",
      triggered_by: [
        "Building (Forms) Regulations 2004 - Form 2",
        "National baseline requirement",
      ],
    },
  ];
}

function buildResolvedDocumentTriggers(
  document: ResolveDocumentsResponse["documents"][number],
) {
  return [document.trigger, document.specialist, document.referenceClause].filter(
    (value): value is string => Boolean(value),
  );
}

function mergeReason(current: string, incoming: string) {
  if (!incoming || current.includes(incoming)) {
    return current;
  }

  return `${current} ${incoming}`.trim();
}

function getZoneCategory(zoneType: string | null | undefined) {
  if (!zoneType || typeof zoneType !== "string") return "general";
  const value = zoneType.toLowerCase();
  if (value.includes("residential")) return "residential";
  if (value.includes("commercial") || value.includes("city centre")) return "commercial";
  if (value.includes("industrial")) return "industrial";
  if (value.includes("rural")) return "rural";
  if (value.includes("open space") || value.includes("open")) return "openspace";
  return "general";
}

function normalizeOverlayKey(sourceKey: string): string | null {
  const map: Record<string, string> = {
    liquefaction: "liquefaction",
    flood: "floodHigh",
    flood_ponding: "floodPonding",
    slope: "slopeHazard",
    heritage_item: "heritage",
    heritage_character: "heritageChar",
    residential_character: "residentialChar",
    tsunami: "tsunami",
    coastal_erosion: "coastalErosion",
    coastal_inundation: "coastalInundation",
    protected_vegetation: "protectedVeg",
    notable_trees: "notableTree",
  };
  return map[sourceKey] ?? null;
}

function buildForecastContext(
  address: string,
  checklist: ChecklistResult,
  intake: ProjectIntake | undefined,
): Record<string, unknown> {
  const activeOverlays = Object.entries(checklist.overlays ?? {})
    .filter(([, isActive]) => isActive)
    .map(([key]) => normalizeOverlayKey(key))
    .filter((key): key is string => Boolean(key));

  return {
    address,
    lat: checklist.coordinates?.lat ?? 0,
    lon: checklist.coordinates?.lon ?? 0,
    zoneCategory: getZoneCategory(checklist.zone_info?.zone_type),
    activeOverlays,
    projectType: intake?.projectType ?? "new_dwelling",
    estimatedFloorAreaM2: intake?.estimatedFloorAreaM2 ?? null,
    estimatedConstructionValueNZD: intake?.estimatedConstructionValueNZD ?? null,
    involvesStructuralWork: intake?.involvesStructuralWork ?? false,
    involvesEarthworks: intake?.involvesEarthworks ?? false,
    existingStructureDemolished: intake?.existingStructureDemolished ?? false,
    newRoadAccess: intake?.newRoadAccess ?? false,
    yearOfConstruction: intake?.yearOfConstruction ?? null,
    newServiceConnections: {
      water: intake?.serviceConnectionWater ?? false,
      wastewater: intake?.serviceConnectionWastewater ?? false,
      stormwater: intake?.serviceConnectionStormwater ?? false,
    },
  };
}

function getDocumentsForState(state: ConsentAssessmentRow) {
  return normalizeDocuments(
    state.checklist?.required_documents ?? [],
    state.manualDocuments,
    state.hiddenDocumentIds,
    state.documentOrder,
  );
}

async function insertConsentAttachmentFallback(
  client: ReturnType<typeof browserClient>,
  baseRecord: {
    project_id: string;
    filename: string;
    storage_path: string;
    mime_type: string | null;
    size_bytes: number;
  },
) {
  const { data, error } = await client
    .from("attachments")
    .insert(baseRecord)
    .select("id, filename, storage_path, uploaded_at, size_bytes, mime_type")
    .single();
  if (error || !data) {
    throw error ?? new Error("Unable to record uploaded file.");
  }

  return {
    id: data.id,
    fileName: data.filename,
    fileSize: Number(data.size_bytes ?? baseRecord.size_bytes),
    uploadedAt: data.uploaded_at,
    storagePath: data.storage_path,
    mimeType: data.mime_type ?? null,
  };
}

function formatApiError(payload: unknown): string {
  if (!payload || typeof payload !== "object") return "";
  const detail = (payload as { detail?: unknown }).detail;
  if (typeof detail === "string") return detail;
  if (Array.isArray(detail)) {
    const first = detail[0] as { msg?: unknown; loc?: unknown } | undefined;
    if (!first) return "Validation error";
    const message = typeof first.msg === "string" ? first.msg : "Validation error";
    const loc = Array.isArray(first.loc) ? first.loc.join(".") : "";
    return loc ? `${loc}: ${message}` : message;
  }
  return "";
}
